"""Utilities for reproducible sparse-view infrared experiments."""

from .contracts import (
    BASE_SPLIT_KIND,
    DATASET_KIND,
    MANIFEST_HASH_FIELD,
    SCHEMA_VERSION,
    SPARSE_SPLIT_KIND,
    ManifestValidationError,
    canonical_json_bytes,
    canonical_sha256,
    load_base_split_manifest,
    load_dataset_manifest,
    load_sparse_split_manifest,
    manifest_sha256,
    validate_base_split_manifest,
    validate_dataset_manifest,
    validate_sparse_split_manifest,
    with_manifest_sha256,
    write_manifest,
)
from .splits import (
    DEFAULT_RATIOS,
    GENERATOR_VERSION,
    SUPPORTED_METHODS,
    build_selection_order,
    create_sparse_split_files,
    generate_sparse_split,
    generate_sparse_splits,
    write_sparse_splits,
)

__all__ = [
    "BASE_SPLIT_KIND",
    "DATASET_KIND",
    "DEFAULT_RATIOS",
    "GENERATOR_VERSION",
    "MANIFEST_HASH_FIELD",
    "ManifestValidationError",
    "SCHEMA_VERSION",
    "SPARSE_SPLIT_KIND",
    "SUPPORTED_METHODS",
    "build_selection_order",
    "canonical_json_bytes",
    "canonical_sha256",
    "create_sparse_split_files",
    "generate_sparse_split",
    "generate_sparse_splits",
    "load_base_split_manifest",
    "load_dataset_manifest",
    "load_sparse_split_manifest",
    "manifest_sha256",
    "validate_base_split_manifest",
    "validate_dataset_manifest",
    "validate_sparse_split_manifest",
    "with_manifest_sha256",
    "write_manifest",
    "write_sparse_splits",
]
